#ifndef _PATH_FINDER_H_
#define _PATH_FINDER_H_

#define FINDER_I2C_ADDR 0x01

// Pathfinder commands
#define FINDER_ADD_NODE 0x01
#define FINDER_GET_PATH 0x02
#define FINDER_START_DISCOVERY 0x03
#define FINDER_GET_DISCOVERY_STATS 0x04
#define FINDER_GET_NEIGHBOR_REQUEST 0x05
#define FINDER_ITERATOR_NEXT 0x06
#define FINDER_ITERATE_NEXT 0x07

class PathFinder
{

};

#endif _PATH_FINDER_H_